# Generated by Django 2.0.13 on 2019-06-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190612_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='data_time',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
    ]
