# Generated by Django 2.0.13 on 2019-06-03 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
