# Generated by Django 2.0.13 on 2019-06-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_text',
            field=models.CharField(max_length=400),
        ),
    ]
