# Generated by Django 2.0.13 on 2019-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190604_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
