# Generated by Django 2.0.13 on 2019-06-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('M', 'On moderation'), ('C', 'Checked'), ('R', 'Rejected')], default='M', max_length=1),
        ),
    ]
