# Generated by Django 2.0.13 on 2019-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
