# Generated by Django 2.0.13 on 2019-06-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190613_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm',
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
