# Generated by Django 2.0.13 on 2019-06-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190613_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_confirm',
            new_name='confirm',
        ),
    ]
